version: '3.8'

services:
  smarthome-api:
    image: hajoui/smarthome-api:1.0
    build:
      context: .
      dockerfile: smarthome/Dockerfile
    network_mode: host
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/rfkill
      - /dev/snd
    volumes:
      - /run/dbus:/run/dbus                                # ✅ correcte mount
      - /run/user/1000:/run/user/1000
      - /run/user/1000/pulse:/run/user/1000/pulse
      - .//wwwroot:/app/wwwroot
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket  # ✅ correcte pad
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    ports:
      - "5000:8080"

  smartfront:
    image: hajoui/smartfront:1.0
    build:
      context: ./SmartFront
      dockerfile: Dockerfile
    ports:
      - "5600:80"
    depends_on:
      - smarthome-api
    networks:
      - smarthome-net

networks:
  smarthome-net:
    driver: bridge
